package com.extinguidor.model.enums;

public enum MaterialCategory {
    HERRAMIENTA_ELECTRICA,
    HERRAMIENTA_MANUAL,
    HERRAMIENTA_NEUMATICA,
    MATERIAL_SEGURIDAD,
    MATERIAL_LIMPIEZA,
    MATERIAL_CONSTRUCCION,
    MATERIAL_ELECTRICO,
    MATERIAL_FONTANERIA,
    MATERIAL_CARPINTERIA,
    MATERIAL_PINTURA,
    EQUIPO_PROTECCION,
    OTROS
}

